version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: eurovision_shop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YAROSLAV0401
      POSTGRES_DB: EurovisionShopDb
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: eurovision_shop_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=EurovisionShopDb;Username=postgres;Password=YAROSLAV0401